# Site settings
title: Tom Sercu
email: tom.sercu@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    My personal web page and blog.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://tom.sercu.me" # the base hostname & protocol for your site
twitter_username: TomSercu
github_username:  tomsercu
timezone: America/New_York

# Build settings
markdown: kramdown

# defaults
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Tom Sercu"
